# Generated by Django 4.2.9 on 2024-01-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Post Thumbnails'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
