# Generated by Django 4.2.9 on 2024-05-23 13:02

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_thumbnail_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Url of the post', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='This is a image field to show the image in the list and in the beginning of the post', null=True, upload_to='Post Thumbnails'),
        ),
    ]
